---
version: "3.8"
services:
  web-ui:
    image: nodejs:20.10-alpine3.19
    container_name: sprinkler-controller-web-ui
    ports:
      - "3000:3000"
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped

  controller-service:
    image: golang:1.21.5-alpine3.19
    container_name: sprinkler-controller-service
    ports:
      - "8080:8080"
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped

  db:
    image: postgres:16.1-alpine3.19
    container_name: sprinkler-controller-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: sprinkler_controller
    volumes:
      - sprinkler-controller-db:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  sprinkler-controller-db: